% This File is generated by U. Cem Kaya - Spring 2019
%% This function Plots the PREM layers on the Area Map
function figHandle = PREMplot(PREM,GridMapParam)
PREM_matrix = PREM.layer1;
mapSize = GridMapParam.mapSize;
X = GridMapParam.X_mesh;
Y = GridMapParam.Y_mesh;

figHandle = figure('Visible', 'on');
axis([mapSize(1,1) mapSize(2,1) mapSize(1,2) mapSize(2,2)]);
hold on , grid on

n = 2; % choose whether you want to project the map as Surface or Contour

switch n
    %% Plot the PREM as a Surface Map
    case 1 
                 
        ax = gca;               % get the current axis
        ax.Clipping = 'off';    % turn clipping off
        % if the Background Image exists, use below
        % img = imread('Scenario11','jpg');
        % imagesc([mapSize(1,1) mapSize(2,1)], [mapSize(1,2) mapSize(2,2)], flipud(img));
        % hold on;
        
        h = surf(X,Y,PREM_matrix);
        caxis([min(PREM_matrix(:))-.5*range(PREM_matrix(:)),max(PREM_matrix(:))]);
        set(h, 'EdgeColor', 'k','LineStyle', '-','LineWidth', 0.001,'EdgeAlpha',0.00);
        light               % create a light
        lighting gouraud    % preferred method for lighting curved surfaces
        set(h, 'FaceLighting','gouraud','EdgeLighting','gouraud');
        material dull
        alpha(h,1)
        legend('off'); colormap jet; view(2);
        
        title('\bf Probabilistic Risk Exposure Map - Top View')
        xlabel(' X, km');ylabel(' Y, km')
        
        drawnow;
    
 %% Plot the PREM as a Contour Map
    case 2
        
        figure(figHandle)
        contourf(X,Y,PREM_matrix,'-');
        
        caxis([min(PREM_matrix(:))-.5*range(PREM_matrix(:)),max(PREM_matrix(:))]);

        legend('off'); colormap jet; view(2);
        
        title('\bf Probabilistic Risk Exposure Map - Top View')
        xlabel(' X, km');ylabel(' Y, km')
        
        drawnow;
end


end